from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1362, 1671)
        MainWindow.setStyleSheet(
            "QTabBar::tab { width: 200px; } QMenuBar::item  { padding-left: 25px;   padding-right: 20px; }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1361, 1391))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tableView = QtWidgets.QTableView(self.tab_1)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 661, 1061))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.textEdit_recorder = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit_recorder.setGeometry(QtCore.QRect(680, 40, 661, 1061))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_recorder.setFont(font)
        self.textEdit_recorder.setObjectName("textEdit_recorder")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_1)
        self.scrollArea.setGeometry(QtCore.QRect(10, 1220, 661, 81))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 79))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton_delete = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_delete.setGeometry(QtCore.QRect(460, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_play = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_play.setGeometry(QtCore.QRect(190, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        self.pushButton_play.setFont(font)
        self.pushButton_play.setObjectName("pushButton_play")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_1)
        self.scrollArea_2.setGeometry(QtCore.QRect(680, 1220, 651, 80))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea_2.setFont(font)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 649, 78))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.pushButton_submit = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_submit.setGeometry(QtCore.QRect(450, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.pushButton_record = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_record.setGeometry(QtCore.QRect(190, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        self.pushButton_record.setFont(font)
        self.pushButton_record.setObjectName("pushButton_record")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(10, 0, 401, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(680, 0, 401, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        self.label_7.setGeometry(QtCore.QRect(680, 1140, 181, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_file = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_file.setGeometry(QtCore.QRect(200, 1140, 471, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_file.setFont(font)
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.lineEdit_recorder = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_recorder.setGeometry(QtCore.QRect(870, 1140, 471, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_recorder.setFont(font)
        self.lineEdit_recorder.setObjectName("lineEdit_recorder")
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        self.label_8.setGeometry(QtCore.QRect(10, 1140, 181, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_transcribe = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_transcribe.setGeometry(QtCore.QRect(200, 1140, 471, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_transcribe.setFont(font)
        self.lineEdit_transcribe.setObjectName("lineEdit_transcribe")
        self.textEdit_realtime = QtWidgets.QTextEdit(self.tab)
        self.textEdit_realtime.setGeometry(QtCore.QRect(680, 40, 661, 1061))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_realtime.setFont(font)
        self.textEdit_realtime.setObjectName("textEdit_realtime")
        self.lineEdit_realtime = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_realtime.setGeometry(QtCore.QRect(880, 1140, 461, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_realtime.setFont(font)
        self.lineEdit_realtime.setObjectName("lineEdit_realtime")
        self.textEdit_transcribe = QtWidgets.QTextEdit(self.tab)
        self.textEdit_transcribe.setGeometry(QtCore.QRect(10, 40, 661, 1061))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_transcribe.setFont(font)
        self.textEdit_transcribe.setObjectName("textEdit_transcribe")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(680, 1140, 191, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 1140, 181, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(680, 0, 401, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(10, 0, 401, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_4.setGeometry(QtCore.QRect(10, 1220, 1331, 80))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea_4.setFont(font)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1329, 78))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.pushButton_end = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_end.setGeometry(QtCore.QRect(870, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_end.setFont(font)
        self.pushButton_end.setObjectName("pushButton_end")
        self.pushButton_begin = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton_begin.setGeometry(QtCore.QRect(190, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_begin.setFont(font)
        self.pushButton_begin.setObjectName("pushButton_begin")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_live = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_live.setGeometry(QtCore.QRect(680, 40, 661, 1061))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_live.setFont(font)
        self.textEdit_live.setObjectName("textEdit_live")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 1220, 1331, 80))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea_3.setFont(font)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1329, 78))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.pushButton_stop = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_stop.setGeometry(QtCore.QRect(860, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_live = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_live.setGeometry(QtCore.QRect(190, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_live.setFont(font)
        self.pushButton_live.setObjectName("pushButton_live")
        self.pushButton_finish = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_finish.setGeometry(QtCore.QRect(1130, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_finish.setFont(font)
        self.pushButton_finish.setObjectName("pushButton_finish")
        self.pushButton_continue = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_continue.setGeometry(QtCore.QRect(460, 10, 150, 60))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_continue.setFont(font)
        self.pushButton_continue.setObjectName("pushButton_continue")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 401, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_final = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_final.setGeometry(QtCore.QRect(10, 40, 661, 1061))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_final.setFont(font)
        self.textEdit_final.setObjectName("textEdit_final")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(680, 0, 401, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_final = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_final.setGeometry(QtCore.QRect(200, 1140, 471, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_final.setFont(font)
        self.lineEdit_final.setObjectName("lineEdit_final")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 1140, 181, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_live = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_live.setGeometry(QtCore.QRect(870, 1140, 471, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_live.setFont(font)
        self.lineEdit_live.setObjectName("lineEdit_live")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(680, 1140, 181, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_5.setGeometry(QtCore.QRect(0, 1390, 1361, 191))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        self.scrollArea_5.setFont(font)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1359, 189))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.lineEdit_progress = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_progress.setGeometry(QtCore.QRect(200, 110, 1141, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_progress.setFont(font)
        self.lineEdit_progress.setText("")
        self.lineEdit_progress.setObjectName("lineEdit_progress")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 181, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_status = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.lineEdit_status.setGeometry(QtCore.QRect(200, 40, 1141, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_status.setFont(font)
        self.lineEdit_status.setText("")
        self.lineEdit_status.setObjectName("lineEdit_status")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 181, 40))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1362, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuqt_ui = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        font.setPointSize(12)
        self.menuqt_ui.setFont(font)
        self.menuqt_ui.setObjectName("menuqt_ui")
        self.menutest_ui = QtWidgets.QMenu(self.menubar)
        self.menutest_ui.setObjectName("menutest_ui")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionproperties = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        self.actionproperties.setFont(font)
        self.actionproperties.setObjectName("actionproperties")
        self.actionimport = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        self.actionimport.setFont(font)
        self.actionimport.setObjectName("actionimport")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Regular")
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.menuqt_ui.addAction(self.actionimport)
        self.menutest_ui.addAction(self.actionproperties)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuqt_ui.menuAction())
        self.menubar.addAction(self.menutest_ui.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Whisper Real Time"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete"))
        self.pushButton_play.setText(_translate("MainWindow", "Play"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.pushButton_record.setText(_translate("MainWindow", "Record"))
        self.label.setText(_translate("MainWindow", "File List"))
        self.label_2.setText(_translate("MainWindow", "Recorder Result"))
        self.label_7.setText(_translate("MainWindow", "Recorder Status"))
        self.label_8.setText(_translate("MainWindow", "File Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "STT Recorder"))
        self.label_9.setText(_translate("MainWindow", "Real Time Status"))
        self.label_10.setText(_translate("MainWindow", "Trascribe Status"))
        self.label_11.setText(_translate("MainWindow", "Real Time Result"))
        self.label_12.setText(_translate("MainWindow", "Trascribe  Result"))
        self.pushButton_end.setText(_translate("MainWindow", "End"))
        self.pushButton_begin.setText(_translate("MainWindow", "Begin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "STT Real Time"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_live.setText(_translate("MainWindow", "Live"))
        self.pushButton_finish.setText(_translate("MainWindow", "Finish"))
        self.pushButton_continue.setText(_translate("MainWindow", "Continue"))
        self.label_3.setText(_translate("MainWindow", "Final Result"))
        self.label_4.setText(_translate("MainWindow", "Live Result"))
        self.label_5.setText(_translate("MainWindow", "Final Status"))
        self.label_6.setText(_translate("MainWindow", "Live Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "STT Live"))
        self.label_13.setText(_translate("MainWindow", "Progress Bar"))
        self.label_14.setText(_translate("MainWindow", "Status Console"))
        self.menuqt_ui.setTitle(_translate("MainWindow", "File"))
        self.menutest_ui.setTitle(_translate("MainWindow", "Setting"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionproperties.setText(_translate("MainWindow", "Properties"))
        self.actionimport.setText(_translate("MainWindow", "Import"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
